version: '3'

services:
  web:
    image: node:14
    working_dir: /app
    volumes:
      - ./app:/app
      - ./mongodb:/mongodb
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    command: node server.js
